### PR TITLE
Fix issues with SVG

### PR DESCRIPTION
**Pull request by SiamKreative**
## Current Status
- [x] Fix error `Uncaught TypeError: target.className.replace is not a function` in [dist/wow.js](https://github.com/matthieua/WOW/blob/master/dist/wow.js#L362). See 663453b
- [ ] Fix warning `'SVGElement.offsetTop' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.`
- [ ] Fix warning `'SVGElement.offsetParent' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.`
## References

http://stackoverflow.com/a/10257755/1414881
https://www.chromestatus.com/features/5724912467574784
https://bugs.chromium.org/p/chromium/issues/detail?id=463116
## Comments
- While I had a few minutes to fix the warning, I don't think I will have time to fix the two warnings related to `SVGElement.offsetTop` and `SVGElement.offsetParent`. It should be a pretty easy fix, just detect if the element is an SVG using the same method and then use `getBoundingClientRect()`.
- I have no idea why the generated **dist/wow.js** also modified the `animationName` function.
- Another way to fix both the issue and warnings would be to wrap the SVG elements in a span but I wouldn't recommend it.

### CODE REVIEW

**Comment by SiamKreative** [comment]
While this pull request solves the error, it would be great to fix the two warnings altogether. Any help will be appreciated.

**Comment by TheWebTech** [comment]
Does this fix the same thing as https://github.com/matthieua/WOW/issues/185#issuecomment-319997317
?

**Comment by juri33** [comment]
Can somebody merge this one?

**Comment by Showcase-Joz** [comment]
pls merge!!!

**Comment by metalandcoffee** [comment]
I tested the fix for `Uncaught TypeError: target.className.replace is not a function` and it didn't fully work. The error went away but the class list for the `svg` element is completely replaced with `animated` which, in my case, killed my styles. Here's my modifications:

To the `WOW.prototype.resetAnimation` function:
```
    WOW.prototype.resetAnimation = function(event) {
      var target;
      if (event.type.toLowerCase().indexOf('animationend') >= 0) {
        target = event.target || event.srcElement;
        if (target instanceof SVGElement) {
          return target.setAttribute('class', target.getAttribute('class').replace(this.config.animateClass, '').trim());
        } else {
          return target.className = target.className.replace(this.config.animateClass, '').trim();
        }
      }
    };
```

To the `WOW.prototype.show` function:
```
    WOW.prototype.show = function(box) {
      this.applyStyle(box);
      if (box instanceof SVGElement) {
        box.setAttribute('class', box.getAttribute('class') + " " + this.config.animateClass );
      } else {
        box.className = box.className + " " + this.config.animateClass;
      }
      
      if (this.config.callback != null) {
        this.config.callback(box);
      }
      this.util().emitEvent(box, this.wowEvent);
      this.util().addEvent(box, 'animationend', this.resetAnimation);
      this.util().addEvent(box, 'oanimationend', this.resetAnimation);
      this.util().addEvent(box, 'webkitAnimationEnd', this.resetAnimation);
      this.util().addEvent(box, 'MSAnimationEnd', this.resetAnimation);
      return box;
    };
```

Hope this helps!

**Comment by manishsuman** [comment]
This issue comes when you are using custom @keyframes animation in your css. 

To the WOW.prototype.resetAnimation function:

```
WOW.prototype.resetAnimation = function(event) {
      var target;
      if (event.type.toLowerCase().indexOf('animationend') >= 0) {
        target = event.target || event.srcElement;
        if((event.animationName!='myAnimation')){ //myAnimation = your custom animation name
          return target.className = target.className.replace(this.config.animateClass, '').trim();
        }
      }
    };
```

Hope this helps!

**Comment by siamkreative** [comment]
I'm not going to have time to look into this, so closing this PR for now.

**Pull request closed without merging**
