### PR TITLE
Use valid SPDX

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by matthieua** [comment]
Thanks @graingert 👍🏻

**Comment by graingert** [comment]
@matthieua now that you've merged my GPL licensed code you can only distribute wow.js under the GPL. If you want to distribute it commercially please obtain from me a commercial license.

**Comment by matthieua** [comment]
Reverted.

**Comment by graingert** [comment]
consider a https://en.wikipedia.org/wiki/Contributor_License_Agreement

**Comment by matthieua** [comment]
Cool, I'll look into it, thanks.

**Comment by graingert** [comment]
@matthieua also contributors won't be able to distribute their contributions back to you under a non-GPLv3 license. So you'll need to add an exception for that too.

**Comment by graingert** [comment]
license
you'll also need to license 503837aad3 under a license that allows @apansky to license cbf70573552b2 so that you can use it commercially.

**Pull request merged**
