### PR TITLE
Fix MutationObserver with webpack

### PR DESCRIPTION
**Pull request by dvdmarchetti**
If you are using wow.js with webpack the MutationObserver isn't found without window.MutationObserver (because the whole file is encapsulated in a function).

### CODE REVIEW

**Comment by graingert** [comment]
@dvdmarchetti it should be found because "window" is at the top of the Scope Chain

**Comment by graingert** [comment]
```js
var foo = 4;

function () {
    console.log(4);
}
```

**Comment by dvdmarchetti** [comment]
Your point is completely righ, but wow.js works great if used as a standalone lib. With webpack the mutation observer isn't found.
I'm not sure, but I think it's because in webpack each library/dependency gets encapsulated into some anonymous function so the plain 'this.MutationObserver' will return undefined instance.

I tried myself with and without my code addition. It worked only if I place window.MutationObserver in the code.

If you need some test and digging into problem, I can try to find an explaination to this behaviour.
Let me know.

**Comment by graingert** [comment]
@dvdmarchetti this should be fixed in https://graingert.co.uk/WOW/ I've yet to push a release though.

**Comment by graingert** [comment]
@dvdmarchetti 1.2.0 of wow.js is released. This should be fixed.

**Comment by dvdmarchetti** [comment]
Great! I'm gonna test the new version and report the issue if the problem still exists.
Thanks!

**Comment by graingert** [comment]
@dvdmarchetti can you create new issues on https://github.com/graingert/WOW/issues please?

**Comment by dvdmarchetti** [comment]
Sure!

**Comment by simple10** [comment]
This works for me with webpack:

`import WOW from 'imports?this=>window!exports?this.WOW!wowjs';`

Uses imports-loader to set this to window so MutationObserver can be found.

**Pull request closed without merging**
